version: '3.5'

services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - network
    env_file:
      - .env
  
  wordpress:
    container_name: wordpress
    image: wordpress
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    expose:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network
    env_file:
      - .env
    depends_on:
      - mariadb


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: "${MYSQL_VOLUME}"
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: "${WP_VOLUME}"
      o: bind

networks:
  network:
